services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: registers
    ports:
      - "5432:5432"
